# Generated by Django 3.1.5 on 2021-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapi', '0002_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
        migrations.AddField(
            model_name='character',
            name='karakter_name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
