# Generated by Django 3.1.5 on 2021-01-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapi', '0003_auto_20210130_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='cls',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.AddField(
            model_name='character',
            name='karakter_class',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='karakter_gender',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='karakter_race',
            field=models.CharField(default='', max_length=32),
        ),
    ]
