# Generated by Django 3.1.5 on 2021-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapi', '0004_auto_20210131_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='karakter_faction',
            field=models.CharField(default='', max_length=32),
        ),
    ]
